### ISSUE TITLE
Jenkins container

### ISSUE THREAD

**Issue by netformic** [claranet/spryker-demoshop#16]
Hi,

what are your plans regarding Jenkins? Currently, it is not working at all, because the Jenkins instance is not able to execute the PHP scripts.

Imho, the correct setup would be to have Jenkins call the Zed instance to execute the scripts.
I have figured out a scripted setup that we currently execute after the initial "docker/run prod build":

adjust **config/Zed/cronjobs/cron.conf** with **PHP_BIN="/usr/local/bin/php"**

attach to zed instance: docker/run prod enter zed

on the zed instance execute:

```
apk update
apk add openjdk8-jre
wget http://jenkins:8080/jnlpJars/jenkins-cli.jar
wget http://jenkins:8080/jnlpJars/slave.jar
cat <<EOF | java -jar jenkins-cli.jar -s http://jenkins:8080/ create-node zed
<slave>
  <name>zed</name>
  <description></description>
  <remoteFS>/data/shop</remoteFS>
  <numExecutors>1</numExecutors>
  <mode>NORMAL</mode>
  <retentionStrategy class="hudson.slaves.RetentionStrategy$Always"/>
  <launcher class="hudson.slaves.JNLPLauncher"/>
  <label>zed</label>
  <nodeProperties/>
</slave>
EOF
java -jar jenkins-cli.jar -s http://jenkins:8080/ offline-node ""
java -jar slave.jar -jnlpUrl http://jenkins:8080/computer/zed/slave-agent.jnlp &
vendor/bin/console setup:jenkins:generate
```

I am currently looking into where this would best fit into the current build scripts.

**Comment by fuhbar** [comment]
Hi @netformic, 

thanks for your suggestion. This actually is still something we need to come up with a properly integrated solution yet. But your idea fits very well. Will think about this and give you feedback ASAP.

regards

**Comment by fuhbar** [comment]
I am excited about your suggestion and will incorporate your idea. Benefit of this solution is that it is a very good starting point for general purposes working in all environments.

I will prepare a PR and notify you in order to review my changes.

**Comment by fuhbar** [comment]
Hi @netformic, 

it took some time to catch up with the backlog, but we finally arrive here. The following PRs/branches introduce all the necessary changes:
   * https://github.com/claranet/spryker-base/pull/24
   * https://github.com/claranet/spryker-demoshop/pull/18

Please try these changes by:
   1. Pull both repos
   1. Checkout concerning branches
   1. Build images
        - base image: `./scripts/build.sh ./Dockerfiles/Dockerfile-php71-alpine.inc.sh`
        - demoshop image: `./docker/run build`
   1. Create demoshop stack: `./docker/run devel up`

This should create the relevant containers, initialize the jenkins slave and register the build jobs. 

Unfortunately some of the directories are hardcoded in the Spryker Setup bundle, which need some attention of upstream to make it work properly. I've open an issue, see https://github.com/spryker/support/issues/143.

What do think so far?

**Comment by didi-at-work** [comment]
Hi @fuhbar ,

nice! Installs flawlessly for me - my setups execute jenkins-tasks on the zed instance itself, but I also considered building a separate jenkins-slave instance, like you do now.

Regarding the hardcoded directories, I used prod mode for my docker setups (and modified the prod-compose-file), because Spryker then creates slightly different jenkins tasks:


```
[ -f /data/shop/deploy/vars ] && . /data/shop/deploy/vars
export APPLICATION_ENV=production
export APPLICATION_STORE=DE
cd $destination_release_dir
. ./config/Zed/cronjobs/cron.conf
$PHP_BIN vendor/bin/console collector:storage:export
```
instead of:
```
export APPLICATION_ENV=development
export APPLICATION_STORE=DE
cd /data/shop/development/current
. ./config/Zed/cronjobs/cron.conf
$PHP_BIN vendor/bin/console collector:storage:export
```
Since it does never change, I put
`destination_release_dir=/data/shop`
into docker/docker-compose.env, and do not really use the /data/shop/deploy/vars file.

I guess we might need a third pre-defined environment ("integration"?), because "development" is tightly coupled to the vagrant-local-VM setup.

P.S.: I was the creator of this issue, but was logged in with the anonymous company account at that moment :)

**Comment by fuhbar** [comment]
Hi @didi-at-work, 

its good to hear that everything worked out smoothly so far. :)

Yes, you are right regarding the cron jobs which are different between `production` and `development`. Since I am optimistic that upstream will fix this any time soon, I've introduced a temporary hack to circumvent these hardcoded path issues. See 6757c2a44393c8123d6f096ebf29d9db468a2948 for that.

Perhaps we should think about a different environment. But this tight coupling is something which needs to be broken up. And for this very purpose it is helpful to stumble over issues like the one we're discussing here.

Thanks again for providing helpful and valuable feedback! :)
