### ISSUE TITLE
(OMS) GraphViz dot not available

### ISSUE THREAD

**Issue by Evil-Devil** [claranet/spryker-demoshop#6]
Hi, I pulled the latest available demoshop image and was impressed by the work that is done. Unfortunately the OMS drawing in Yves (maintenance -> oms) is not fully functional as drawing the graph throws an exception "An error occurred while creating the graph; GraphViz returned: sh: dot: not found"

I checked the container and it seems that graphviz is not installed. I wasn't able yet to install it on my own and it would be great to have it available in the package to everyone, so one can fully use OMS :)

**Comment by Evil-Devil** [comment]
So, managed to install graphviz in both containers and the OMS draws the graph.
Adding `RUN apk --no-cache graphviz` in the dockerfile should be enough.

The question I'm asking myself is now where to put it? spryker-base or here in spryker-demoshop? I can create a pull request as soon as I know where to put it.

**Comment by fuhbar** [comment]
Thanks for your interest in our work. We are keen to get feedback in order to improve the quality and gain maturity.

The bug you have reported is indeed something we've missed. I am currently working this out and will prepare a PR. 

I would recommend putting this into the base image due to the facts that OMS is pretty much common across different Spryker shop scenarios. For this I will make variables for installing base and build dependencies more explicitly available.

**Comment by fuhbar** [comment]
@Evil-Devil Added `graphviz` to  `COMMON_BASE_DEPENDENCIES` in spryker-base image.

Please test this change and check if it works. The image is reachable via `:latest` tag.

**Comment by Evil-Devil** [comment]
@fuhbar Great! I pulled and tested the new image. OMS works fine so far and hopefully there won't be another issue with it ;) Thanks for your effort, I highly appreciate it.
